name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Server via SCP
      env:
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        sudo apt-get install sshpass
        sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -r * $USERNAME@$SERVER:/path/to/your/server/directory

    - name: Restart Flask Application
      run: |
        sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER 'bash /path/to/your/server/restart_flask.sh'
